/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  smtlibSidebar: [
    {
      type: 'category',
      label: 'Logic',
      collapsible: true,
      collapsed: false,
      items: [
        'logic/intro',
        'logic/basiccommands',
        'logic/propositional-logic',
        'logic/Uninterpreted-functions-and-constants',
        'logic/Quantifiers',
        'logic/Lambdas',
        'logic/Recursive Functions',
        'logic/Conclusion'
      ],
    },

    {
      type: 'category',
      label: 'Theories',
      collapsible: true,
      collapsed: true,
      items: [
        'theories/Arithmetic',
        'theories/Bitvectors',
        'theories/IEEE Floats',
        'theories/Arrays',
        'theories/Datatypes',
        'theories/Strings',
        'theories/Sequences',
        'theories/Regular Expressions',
        'theories/Characters',
        'theories/Special Relations'
      ]
    },

    {
      type: 'category',
      label: 'Strategies',
      collapsible: true,
      collapsed: true,
      items: [
        'strategies/intro',
        'strategies/goals',
        'strategies/tactics',
        'strategies/probes',
        'strategies/summary',
	'strategies/simplifiers']
    },

    {
      type: 'category',
      label: 'Optimization',
      collapsible: true,
      collapsed: true,
      items: [
        'optimization/intro',
        'optimization/apioptimization',
        'optimization/arithmeticaloptimization',
        'optimization/softconstraints',
        'optimization/combiningobjectives',
        'optimization/asmallcasestudy',
        'optimization/advancedtopics'
      ]
    },

    {
      type: 'category',
      label: 'FixedPoints',
      collapsible: true,
      collapsed: true,
      items: [
        'fixedpoints/intro',
        'fixedpoints/basicdatalog',
        'fixedpoints/engineforpdr',
        'fixedpoints/syntax'
      ]
    },
  ]

};

module.exports = sidebars;
