#!/usr/bin/env python3

import argparse
from pathlib import Path

GENERATED_DOCUMENTS = {
    "Parameters.md": Path("website/docs-programming/04 - Parameters.md"),
    "tactics-summary.md": Path(
        "website/docs-smtlib/03 - strategies/06 - summary.md",
    ),
    "simplifier-summary.md": Path(
        "website/docs-smtlib/03 - strategies/07 - simplifiers-summary.md",
    ),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import parameter-related Markdown generated by a Z3 release.",
    )
    parser.add_argument(
        "generated_directory",
        type=Path,
        help="Directory containing Markdown generated by the Z3 documentation scripts",
    )
    parser.add_argument(
        "--release-tag",
        required=True,
        help="Z3 release tag used to generate the documentation",
    )
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=Path.cwd(),
        help="z3guide repository root (default: current directory)",
    )
    return parser.parse_args()


def add_source_notice(content: str, release_tag: str) -> str:
    notice = (
        f"<!-- Generated from Z3Prover/z3 release {release_tag}. "
        "Do not edit manually. -->"
    )
    if not content.startswith("---\n"):
        return f"{notice}\n\n{content}"

    frontmatter_end = content.find("\n---\n", 4)
    if frontmatter_end == -1:
        raise ValueError("Generated document has unterminated front matter")
    frontmatter_end += len("\n---\n")
    return (
        f"{content[:frontmatter_end]}\n{notice}\n\n"
        f"{content[frontmatter_end:].lstrip()}"
    )


def main() -> None:
    args = parse_args()
    for generated_name, relative_destination in GENERATED_DOCUMENTS.items():
        source = args.generated_directory / generated_name
        if not source.is_file():
            raise FileNotFoundError(f"Missing generated document: {source}")

        content = source.read_text(encoding="utf-8").replace("\r\n", "\n")
        if not content.strip():
            raise ValueError(f"Generated document is empty: {source}")
        content = "\n".join(line.rstrip() for line in content.splitlines()) + "\n"

        destination = args.repository_root / relative_destination
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("w", encoding="utf-8", newline="\n") as output:
            output.write(add_source_notice(content, args.release_tag))


if __name__ == "__main__":
    main()
