/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  LogicSidebar: {
    Logic: [
      {
      type: 'category',
      label: 'Logic',
      collapsible: true,
      collapsed: false,
      items: [
        'logic/intro','logic/intro', 'logic/basiccommands', 'logic/propositional-logic', 'logic/Uninterpreted-functions-and-constants', 'logic/Quantifiers', 'logic/Lambdas', 'logic/Recursive Functions', 'logic/Conclusion'],
        },
      ],
    },
  
    Theories:[
      {
      type: 'category',
      label: 'Theories',
      collapsible: true,
      collapsed: false,
      items: [ 'theories/Arithmetic','theories/Bitvectors', 'theories/IEEE Floats', 'theories/Arrays', 'theories/Datatypes', 'theories/Strings', 'theories/Sequences', 'theories/Special Relations']
      }
    ], 
    Strategies:[
      {
        type: 'category',
        label: 'Strategies',
        collapsible: true,
        collapsed: false, 
        items: ['strategies/intro','strategies/goals', 'strategies/tactics', 'strategies/probes']
      }
    ],
    Optimization:[
      {
        type: 'category',
        label: 'Optimization',
        collapsible: true,
        collapsed: false,  
        items: ['optimization/intro','optimization/apioptimization', 'optimization/arithmeticaloptimization', 'optimization/softconstraints', 'optimization/combiningobjectives', 'optimization/asmallcasestudy', 'optimization/advancedtopics']
      }
    ],
     FixedPoints:[
      {
        type: 'category',
        label: 'FixedPoints',
        collapsible: true,
        collapsed: false, 
         items: ['fixedpoints/intro','fixedpoints/basicdatalog', 'fixedpoints/engineforpdr', 'fixedpoints/syntax']
       }
     ]
  };

module.exports = sidebars;
