/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  generalSidebar: {
    Logic: [
      {
      type: 'category',
      label: 'Logic',
      collapsible: true,
      collapsed: false,
      items: [
        'logic/intro','logic/intro', 'logic/basiccommands', 'logic/propositional-logic', 'logic/Uninterpreted-functions-and-constants', 'logic/Quantifiers', 'logic/Lambdas', 'logic/Recursive Functions', 'logic/Conclusion'],
        },
      ],
    },
  
    Theories:[
      'theories/Arithmetic',
      {
        Docs: ['theories/Bitvectors', 'theories/IEEE Floats', 'theories/Arrays', 'theories/Datatypes', 'theories/Strings', 'theories/Sequences', 'theories/Special Relations']
      }
    ], 
    Strategies:[
      'strategies/intro',
      {
        Docs: ['strategies/goals', 'strategies/tactics', 'strategies/probes']
      }
    ],
    Optimization:[
      'optimization/intro',
      {
        Docs: ['optimization/apioptimization', 'optimization/arithmeticaloptimization', 'optimization/softconstraints', 'optimization/combiningobjectives', 'optimization/asmallcasestudy', 'optimization/advancedtopics']
      }
    ],
     FixedPoints:[
       'fixedpoints/intro',
       {
         Docs: ['fixedpoints/basicdatalog', 'fixedpoints/engineforpdr', 'fixedpoints/syntax']
       }
     ]
  };

  // programmingZ3Sidebar:{
  //   Python:[
  //     'programming Z3/Using Z3 from Python',
  //     {
  //       Docs: []
  //     }
  //   ]
  // },

module.exports = sidebars;
