name: Execute z3py snippets in the documentation

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  execute-z3py-snippets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.14"
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip install -r scripts/requirements-check-z3py-docs.txt
      - name: execute the pyz3 snippets found in the documentation
        run: |
          # Generate a summary for the job.
          # reference: https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/
          scripts/check-z3py-docs.py \
            "website/docs-programming/02 - Z3 Python" \
            --recursive \
            >> $GITHUB_STEP_SUMMARY
          scripts/check-z3py-docs.py \
            "website/docs-programming/03 - Example Programs/01 - Cores and Satisfying Subsets.md" \
            >> $GITHUB_STEP_SUMMARY
